spring:
  application:
    name: coaching_center_offline_support

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${BREVO_HOST}
    port: ${BREVO_PORT}
    password: ${BREVO_PASSWORD}
    username: ${BREVO_USERNAME}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


aws:
  region: ap-south-1
  bucketName: coaching-offline-v2
  credentials:
    secret-key: ${AWS_SECRET_KEY}
    access-key: ${AWS_ACCESS_KEY}


jwt:
  security: ${JWT_SECURITY}
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: INFO